# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

# For some reason the generated TODO didn't take these into account, so we exclude them manually.
# We don't want to add them to the TODO file itself, to maintain `--regenerate-todo` compatibility.
Naming/MethodName:
  Exclude:
    - lib/irb.rb
    - lib/irb/ext/multi-irb.rb
    - lib/irb/locale.rb
Naming/VariableName:
  Exclude:
    - lib/irb/ext/multi-irb.rb
    - lib/irb/extend-command.rb
    - lib/irb/init.rb
    - lib/irb/version.rb
# End of amended TODO
